default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: surf_spots_development
test:
  <<: *default
  database: surf_spots_test
production:
  <<: *default
  database: surf_spots_production
  username: surf_spots
  password: <%= ENV['SURF_SPOTS_DATABASE_PASSWORD'] %>
